### PR TITLE
feat: add client context

### PR DESCRIPTION
**Pull request by joway**
In the previous implementation, we could only set header with protocol, which makes it hard to implement a multiplexing client that could send RPC calls concurrently. Since our server already has a context processor implement, so we think there should also have a corresponding implementation on the client-side.

### CODE REVIEW

**Comment by vitaut** [comment]
Thanks for the PR and sorry for slow response. If you are still interested in having it reviewed could you rebase the PR and fix merge conflicts?

**Comment by joway** [comment]
@vitaut hi, merged. Thanks for review.

**Comment by codyohl** [comment]
not clear to me what the goal is here - it is trying to extract Headers from context (which, from the client side, depends on a protocol context key in the context, which is only inserted from the server implementations) and setting those headers on the underlying protocol for the request. In order to propogate a custom header to the server through context, you'd have to manually construct a thrift.HeaderProtocol and use the WithProtocol function to attach it. Seems cumbersome? am I missing something?
In addition, this new code leaks the Header out of the Protocol abstraction, which i know happens elsewhere but it didn't previously happen in this file.
Overall, I agree that ctx should be included in clients, but it's not clear to me that this should be the way we should map context values to the header map. If we agree this is the way we should do it, it still doesn't support some useful common uses of context (like deadlining and server preemption).
question: what's wrong with going toward the abstractions made by C++ and implementing a go channel client capable of multiplexing using the new RequestChannel API? It might be closer to what you are looking for and it already includes ctx in the calls.
```
type RequestChannel interface {
	ClientInterface

	Call(ctx context.Context, method string, request IRequest, response IResponse) error
	Oneway(ctx context.Context, method string, request IRequest) error
}
```

**Comment by joway** [comment]
@codyohl hi, RequestChannel is a new API which not exists when I create this PR. I think it's better to follow the Cpp abstractions, so there is no need to change the client implement.

**Pull request closed without merging**
