### PR TITLE
 Fix travis build

### PR DESCRIPTION
**Pull request by kornrunner**
Remove duplicate Struct.pxd.mustache

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by kornrunner** [comment]
Also fixed travis build in following commit

**Comment by kornrunner** [comment]
Seems first chunk got in via 1d53cd97597ed94e6b1d924657d42a0586c850f7

**Comment by jesboat** [comment]
@facebook-github-bot shipit

**Comment by jesboat** [comment]
hey @kornrunner, thanks for fixing this!

**Comment by kornrunner** [comment]
@jesboat thank you for reviewing and merging it!

**Pull request closed without merging**
