### PR TITLE
Use THRIFT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

### PR DESCRIPTION
**Pull request by alex-700**
to make it work in add_subdirectory environment

### CODE REVIEW

**Review by vitaut — CHANGES_REQUESTED** [review]
Thanks for the PR. Please use `THRIFT_SOURCE_DIR` instead of `THRIFT_HOME`. The latter should really be removed because it's redundant and doesn't specify if it refers to source or binary.

**Comment by alex-700** [comment]
> Thanks for the PR. Please use `THRIFT_SOURCE_DIR` instead of `THRIFT_HOME`. The latter should really be removed because it's redundant and doesn't specify if it refers to source or binary.

Hi, @vitaut ! Yeap, it is a good idea!

Did you, actually, mean `fbthrift_SOURCE_DIR`? because I don't see `project(thrift ...)` call, only `project(fbthrift ...)` one... And also it is case-sensitive... 

And maybe it is a better to use name-agnostic `PROJECT_SOURCE_DIR` instead? But it quite depends on project structure (will you plan to use `project` on subdirectories often, or not). What do you think?

**Comment by alex-700** [comment]
- Decided to change to `fbthrift_SOURCE_DIR` (checked in my environment, it works like with THRIFT_HOME before).
- @vitaut  I'm pretty sure (but in static sense: I don't check it :) ) that using `THRIFT_SOURCE_DIR` is a bug (this variable seems to be empty), so decided to fix this too.

**Comment by alex-700** [comment]
> Good idea if PROJECT_SOURCE_DIR refers to the innermost project. We don't plan to use project in subdirectories.

hmm... No, the [documentation](https://cmake.org/cmake/help/v3.24/variable/PROJECT_SOURCE_DIR.html) says, that 
> Note, it is not affected by calls to [project()](https://cmake.org/cmake/help/v3.24/command/project.html#command:project) made within a child directory scope (i.e. from within a call to [add_subdirectory()](https://cmake.org/cmake/help/v3.24/command/add_subdirectory.html#command:add_subdirectory) from the current scope).

So, sorry, my bad :) It is not a good idea here.

So lets accept this MR and will use `fbthrift_SOURCE_DIR`.

**Comment by alex-700** [comment]
> The project name has been changed to `THRIFT` in [24e2118](https://github.com/facebook/fbthrift/commit/24e211882216f3cc61ec1786159d3195b671d074). Please rebase and use `THRIFT_SOURCE_DIR`.

:heavy_check_mark:

**Comment by vitaut** [comment]
Merged, thank you!

**Pull request closed without merging**
