### PR TITLE
feat: support pyodide on bypass fcntl call

### PR DESCRIPTION
**Pull request by wey-gu**
For fbthrift python on jupyterlite/pyodide, [fcntl is not yet supported]( https://github.com/pyodide/pyodide/discussions/4150) , it's worth bypassing it in such cases similar to the Windows case.

### CODE REVIEW

**Comment by vitaut** [comment]
@wey-gu, sorry for slow reply. I wonder why is this not covered by the `fcntl is None` check above?

**Comment by wey-gu** [comment]
> @wey-gu, sorry for slow reply. I wonder why is this not covered by the `fcntl is None` check above?

Dear @vitaut 

Thanks for the reply!

It's due to fcntl can be imported in such case(thus it's actually not None) just it failed later with exception:

```
module 'fcntl' has no attribute 'fcntl'
```

**Comment by wey-gu** [comment]
Sorry for the long wait again, @vitaut I addressed the improved impl as you suggested :), Thanks!

**Comment by vitaut** [comment]
Merged, thanks!

**Pull request closed without merging**
