### PR TITLE
Fix m4 and travis

### PR DESCRIPTION
**Pull request by seanfarley**
When I updated configure.ac I didn't realize that most systems don't have the autoconf-archive package (nor should they, really). Instead, let's copy the needed files into the repo so we can have a portable build.

### CODE REVIEW

**Comment by seanfarley** [comment]
`/usr/bin/ld: cannot find -l-L/opt/python/2.7.10/lib`

Hmmm, perhaps I should revert the updates to ax_boost_python?

**Comment by seanfarley** [comment]
Testing the build without the previous updates to ax_boost_{base,python}. If this passes, then feel free to merge.

**Comment by lukenels** [comment]
(The failing Travis build seems unrelated to this fix for the boost problem)

**Comment by seanfarley** [comment]
Ah, that's good to hear!

**Pull request closed without merging**
